### ISSUE TITLE
Dependency issue with phoenix live view

### ISSUE THREAD

**Issue by jpea72** [akira/exq_ui#108]
I'm running Live View 0.17.5, and version 12 is locked on `exq_ui (version 0.12.0) requires ~> 0.16.0`

Can the dependency be bumped to allow for version PLV 17?

**Comment by ananthakumaran** [comment]
There are some breaking changes related to the stateful component in 0.17. Need to make relevant changes before we can relax the requirement. I will try to check over the weekend
