### ISSUE TITLE
setting live_socket_path option in live_exq_ui does not work

### ISSUE THREAD

**Issue by ryanlchandler** [akira/exq_ui#118]
In phoenix router.ex setting option `:live_socket_path` to "/myapp/exq/live"
```
defmodule DemoWeb.Router do
  use Phoenix.Router
  import ExqUIWeb.Router

  pipeline :browser do
    plug :fetch_session
    plug :protect_from_forgery
  end

  scope "/", DemoWeb do
    pipe_through :browser

    live_exq_ui("/myapp/exq", [live_socket_path: "/myapp/exq/live"])
  end
end
```

However, web socket requests continue going to `/live`

---

I think this is because app.js is hard coded to `/live`

https://github.com/akira/exq_ui/blob/7d561d717d1dc594916a1065696d0d3fbf729ed1/assets/js/app.js#L28

Not sure if this is a bug or I'm doing something wrong, please advise.

**Comment by ananthakumaran** [comment]
could you try this fix https://github.com/akira/exq_ui/pull/119

**Comment by ryanlchandler** [comment]
That worked!  Thanks @ananthakumaran !!

**Comment by williamweckl** [comment]
Has this fix being released to hex?

**Comment by ananthakumaran** [comment]
Not yet. @akira could you cut a release when you have time.

**Comment by akira** [comment]
Just released, thanks for the heads up! 👍
