### ISSUE TITLE
Not compatible with LiveView 0.18

### ISSUE THREAD

**Issue by williamweckl** [akira/exq_ui#131]
After an update of live view dep of my app, I got this error:

```
== Compilation error in file lib/exq_ui_web/views/layout_view.ex ==
** (CompileError) lib/exq_ui_web/templates/layout/live.html.heex:1: undefined function live_component/1 (expected ExqUIWeb.LayoutView to define such a function or for it to be imported, but none are available)

could not compile dependency :exq_ui, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile exq_ui", update it with "mix deps.update exq_ui" or clean it with "mix deps.clean exq_ui"
```

Using LiveView 0.17 there was some warnings of the function `live_component` being deprecated. Looks like they have removed it at the new version.

Instead of using `<%= live_component SomeComponent, id: "someid" %>` ExqUI need to be changed to use `<.live_component module={SomeComponent} id="someid" />`.

The change was being made at 0.17.0 according to their changelog: https://github.com/phoenixframework/phoenix_live_view/blob/master/CHANGELOG.md#enhancements-9

**Comment by williamweckl** [comment]
I'm seeing that probably the issue was already solved by https://github.com/akira/exq_ui/commit/3c03bbaa7caaaee9f5983ba36025bf302424c13d .

Maybe you just need to release an updated of the lib at hex.pm. :)

**Comment by ananthakumaran** [comment]
@akira could you cut a release

**Comment by akira** [comment]
@ananthakumaran sorry missed this, I just released.  Also, FYI, I added github workflow to cut release on new tag pushes which can be used in future.
