### ISSUE TITLE
Jobs with errors causes worker to unsubscribe from all queues

### ISSUE THREAD

**Issue by colman-hartinger** [akira/exq_ui#132]
Exq config:
```
  start_on_application: false,
  scheduler_enable: true,
  mode: :default
 
 ###############################
 application.ex
 ###############################
 children = [
   Exq
 ]
```

Description:
A job with a failure that kills the worker process causes the worker node to unsubscribe all the queues indefinitely.

**Comment by ananthakumaran** [comment]
fixed on [v0.13.0](https://github.com/akira/exq_ui/releases/tag/v0.13.0)
