### ISSUE TITLE
Error when getting root route with Phoenix 1.7 and Verified Routes

### ISSUE THREAD

**Issue by alexfilatov** [akira/exq_ui#142]
When phoenix 1.7 with Verified Routes enabled, getting error when requesting `/exq` dashboard - helper here cannot get `:root` route 
https://github.com/akira/exq_ui/blob/master/lib/exq_ui_web/router/helpers.ex#L24

`** (UndefinedFunctionError) function nil.exq_ui_path/2 is undefined`

Root cause is `use Phoenix.Router, helpers: false` in `MyAppWeb.router()`

**Comment by ananthakumaran** [comment]
@alexfilatov could you try the branch https://github.com/akira/exq_ui/pull/143

**Comment by alexfilatov** [comment]
thank you so much @ananthakumaran!
