### ISSUE TITLE
ExqUi and Exrm

### ISSUE THREAD

**Issue by darksheik** [akira/exq_ui#15]
Hi there!

I had previously been lazy and was running my Phoenix app in production using mix to launch directly on the console:
```
MIX_ENV=prod mix phoenix.server
```

Exq and ExqUi both work great with this method.  I am trying to package an [Exrm](http://www.phoenixframework.org/docs/advanced-deployment) release, though, and it compiles fine but then dies when I try to load a page:

```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function: ExqUi.RouterPlug.call/2 (module ExqUi.RouterPlug is not available)
```

I have no idea why the behavior would be any different.  Does anything jump out at you as to why it wouldn't see the ExqUi.RouterPlug module?  I would think it's because I might need to add :exq_ui to my application list, but when I do that the app crashes because it tries to start ExqUi twice.

**Comment by akira** [comment]
Yes, I think it would need to get added to the application list as you mentioned. What is the error displayed in that case? If you can give some info on how you're running it through Exrm and error message (let me know if you have a sample repo).

**Comment by darksheik** [comment]
My sample repo is private, but I can share the basic config:

Configured in prod.exs:

```
config :exq,
  name: Exq,
  host: "<my redis box>",
  port: 6379,
  namespace: "<my_namespace>",
  concurrency: :infinite,
  queues: ["default"],
  poll_timeout: 50,
  scheduler_poll_timeout: 200,
  scheduler_enable: true,
  max_retries: 0
```

In mix.exs:
Not added to def application at all.  When I do, it tries to start Exq twice.

deps:
```
  defp deps do
    [{:phoenix, "~> 1.1.3"},
     {:phoenix_ecto, "~> 2.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.3"},
     {:phoenix_live_reload, "~> 1.0"},
     {:cowboy, "~> 1.0"},
     {:exq, "~> 0.6.4"},
     {:exq_ui, "~> 0.6.4"},
     {:floki, "~> 0.5"},
     {:exrm, "~> 0.19.9"},
     {:comeonin, "~> 1.0"},
     {:hound, "~> 0.7.6", github: "darksheik/hound", branch: "0.7.6-plus-pr"},
     {:arc, "~> 0.1.4"},
     {:arc_ecto, "~> 0.2.0"},
     {:cryptex, "0.0.1"},
     {:mailman, "~> 0.1.0"},
     {:eiconv, github: "zotonic/eiconv"},
     {:inflex, "~> 1.5.0"},
     {:porcelain, "~> 2.0"},
     {:sshex, "2.0.1"},
     {:csvlixir, "~> 2.0"}]
  end
```

In lib/my_app.ex:

```
  def start(_type, _args) do
    import Supervisor.Spec, warn: false

    children = [
      # Start the endpoint when the application starts
      supervisor(MyApp.Endpoint, []),
      # Start the Ecto repository
      worker(MyApp.Repo, []),

      #Add the Exq supervisor
      supervisor(Exq, [])

      # Here you could define other workers and supervisors as children
      # worker(MyApp.Worker, [arg1, arg2, arg3]),
    ]

    # See http://elixir-lang.org/docs/stable/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: MyApp.Supervisor]
    Supervisor.start_link(children, opts)
  end
```


In both development and production, when I start Phoenix server manually via the command line,

**Comment by akira** [comment]
That recommendation was actually changed in the documentation for Exq - it is no longer recommended to put Exq in the phoenix supervisor hierarchy. What happens if you take that out, and add :exq and :exq_ui to the application list?

**Comment by darksheik** [comment]
Adding just :exq seems to start both ok in Dev.  Adding :exq_ui also tries to start that twice and dies.
I will try repackaging in production after hours and let you know how that goes.  Thanks!

**Comment by darksheik** [comment]
I don't think there's there's an issue actually starting :exq_ui, it just doesn't seem to recognize ExqUi.RouterPlug in my application's router file.

When I comment out these lines in web/router.ex, everything works fine:

```
    plug ExqUi.RouterPlug, namespace: "exq"
    forward "/exq", ExqUi.RouterPlug.Router, :index
```

Exq is definitely processing things, but I just don't have an interface anymore. :)

**Comment by akira** [comment]
OK that makes sense. I will take a look at this weekend - been busy so haven't gotten a chance yet.

**Comment by akira** [comment]
@darksheik Let me know if this fixes it, seemed to work for me locally.

**Comment by akira** [comment]
bump

**Comment by akira** [comment]
Closing, let me know if this is still an issue and will reopen @darksheik

**Comment by darksheik** [comment]
Apologies, I've been significantly reengineering my app with crazy distributed nodes.  I'll retest as soon as I can.

Thanks for the followup.

**Comment by isaksky** [comment]
I have the same issue (running post #16).

```
Request: GET /exq
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function ExqUi.RouterPlug.call/2 is undefined (module ExqUi.RouterPlug is not available)
```

I didn't include `exq_ui` in the applications list, because then I get an "x has already started" error when starting the app.
