### ISSUE TITLE
UI - allow requeue dead jobs 

### ISSUE THREAD

**Issue by akira** [akira/exq_ui#2]
As an end user, I want to re-enqueue dead jobs in the UI
## Acceptance Criteria
- Add "Requeue" button in dead job UI view for each job
- Clicking on "Requeue" button, requeues dead jobs

**Comment by ananthakumaran** [comment]
![image](https://user-images.githubusercontent.com/149238/152644795-07b9abd9-411a-48b2-b926-ca5cd7ad9fd7.png)
retry now option is available in the latest version
