### ISSUE TITLE
Cancelling Jobs in the retry list

### ISSUE THREAD

**Issue by AaronBetterOfficeApps** [akira/exq_ui#20]
It would be nice to be able to clear jobs out of the retry list manually after they have passed there fail limit. The problem that I'm am running into is if a worker failed and won't actually be able to be retried successfully, it will always be in the retry list and on restart of my elixir application when exq boots up it is runs again only to fail. There is most likely a better way to solve this, but currently I have been flushing redis to clear out the jobs.

**Comment by akira** [comment]
:+1: yeah, this is needed. Was planning on putting this in, but was adding the API for Exq first.

**Comment by akira** [comment]
The API has been merged, so this should be fairly easy to add next.

**Comment by akira** [comment]
Fixed by #24
