### ISSUE TITLE
Prevent server from starting in testing environment

### ISSUE THREAD

**Issue by pdilyard** [akira/exq_ui#21]
Is there a way to prevent the `exq_ui` server from being started when running `mix test`? Phoenix for example provides the `server: false` option in your Endpoint config.

**Comment by akira** [comment]
@pdilyard Work using `mix test --no-start` work for your use case?

**Comment by pdilyard** [comment]
Unfortunately most of my tests will fail with `--no-start`.

**Comment by akira** [comment]
Gotcha, adding a similar `server` config option could work and would be super easy, feel free to PR this or otherwise I have some other things I'm working on but could get to it after those.
