### ISSUE TITLE
Does not work with the new version of Phoenix

### ISSUE THREAD

**Issue by katgironpe** [akira/exq_ui#26]
I am using the new version of Phoenix: 

```elixir
     {:phoenix, "~> 1.2.0-rc"},
     {:phoenix_ecto, "~> 3.0.0-rc.0"},
     {:phoenix_html, "~> 2.5.1"},
     {:phoenix_pubsub, "~> 1.0.0-rc"},
```
With exq_ui, I get this error:

**Router.Helpers is not loaded and could not be found**

**Comment by akira** [comment]
Thanks for reporting.  I've got a lot going on at the moment, so not sure the soonest I'd have time to look at it, but would gladly accept PRs.

**Comment by taylorbrooks** [comment]
Actually mine failure is a little different:

`** (UndefinedFunctionError) function DripEmails.ExqUi.RouterPlug.Router.init/1 is undefined (module DripEmails.ExqUi.RouterPlug.Router is not available)`

Here's my router:

````elixir
  scope "/", DripEmails do
    forward "/exq", ExqUi.RouterPlug.Router, :index
  end
````

It looks like it's prepending my app name to the Exq router plug and it can't find that module.

**Comment by DavidACL** [comment]
I'm getting the same error as @taylorbrooks

**Comment by akira** [comment]
Updated router.ex config for this, see #27

**Comment by katgironpe** [comment]
This fixed it. Thank you!
