### ISSUE TITLE
UI - Scheduled queue delete item button

### ISSUE THREAD

**Issue by akira** [akira/exq_ui#3]
As an end user, I want to delete scheduled job in the UI
## Acceptance Criteria
- Add "Delete" button in scheduled jobs UI view for each job
- Clicking on "Delete" button, removes job from scheduled queue

**Comment by ananthakumaran** [comment]
![image](https://user-images.githubusercontent.com/149238/152644817-8192ef08-3c0c-4c40-a35e-3ea4cd6448f3.png)
delete and delete all option is available in the latest version
