### ISSUE TITLE
Conversion of UI library to React.js

### ISSUE THREAD

**Issue by akira** [akira/exq_ui#32]
Currently this is written in Ember, but it does need continual updating and maintenance given that the dependent libraries are being deprecated / updated.

As a maintainer, I don't have much Ember experience and am personally more familiar with libraries such as React.js.   

I am considering rewrite of the UI to React.js / Redux / React Router.

Alternatives considered:
* Vue.js / Vuex / Vue Router
* Clojurescript (with Reagent or Om.next). 

However, given that React.js seems the most widely used, I am inclined toward React.js and Redux.

**Comment by seivan** [comment]
I would prefer React mostly because it would be easier to isolate and keep dependency and build requirements to a minimum. No need for CSS files or HTML templates. Keep styles and  html (JSX) inline.

**Comment by Rastopyr** [comment]
React.js and similar frameworks is more complicated than Ember. For best experience i I would suggest migrate to latest version of Ember

**Comment by akira** [comment]
Not as crucial with #45 helping update to latest Ember version.

**Comment by akira** [comment]
Closing as no longer on Ember
