### ISSUE TITLE
Allow to see full backtrace in failures

### ISSUE THREAD

**Issue by mspanc** [akira/exq_ui#35]
At the moment UI truncates backtrace in failures and they are useless.

![zrzut ekranu z 2016-12-28 16-16-31](https://cloud.githubusercontent.com/assets/389651/21524789/2a45b354-cd19-11e6-8adb-d2ed15de4bd9.png)

Seems that whole backtrace gets transmitted over the API, so it is purely UI thing.

I suggest adding a link will allow to unwrap the whole backtrace if they are truncated.

**Comment by gchronis** [comment]
Puull request added: #51
