### ISSUE TITLE
Erlang gen_server error when trying to access ExqUI

### ISSUE THREAD

**Issue by vrosancic** [akira/exq_ui#42]
Hi! I have an issue with `exq_ui` package. When I try to access the dashboard, I am getting the `erlang gen_server error: :noproc`. I am running the page through Plug. When I run it on a separate port with `mix exq.ui`, everything works ok.

What is strange is that everything worked ok until a few days ago when it stopped. I have no idea how to solve this.

Here is the whole stack trace:
```
Elixir.ErlangError erlang error: {:noproc, {GenServer, :call, [ExqUi.Api, {:stats, "processed"}, 5000]}} 
    lib/gen_server.ex:596 GenServer.call/3
    web/router.ex:45 anonymous fn/1 in ExqUi.RouterPlug.Router.do_match/4
    web/router.ex:34 ExqUi.RouterPlug.Router.plug_builder_call/2
    lib/phoenix/router/route.ex:154 Phoenix.Router.Route.forward/4
    lib/phoenix/router.ex:261 MyApp.Router.dispatch/2
    web/router.ex:1 MyApp.Router.do_call/2
    lib/plug/error_handler.ex:64 MyApp.Router.call/2
    lib/my_app/endpoint.ex:1 MyApp.Endpoint.phoenix_pipeline/1
```

**Comment by akira** [comment]
Does this still happen consistently, or only once in a while? What version of exq / exq_ui are you running?

**Comment by vrosancic** [comment]
Hi @akira! Yes, it happens consistently. Both exq and exq_ui versions are 0.8.4. I've updated them recently. Previously exq was 0.8.1 and exq_ui 0.8.3.

**Comment by vrosancic** [comment]
Hey @akira, I've just fixed this. I've added `:exq_ui` to the list of applications in `mix.exs` file. Only thing that is strange now is that it starts `ExqUi` on the port 4040 as well. So you can access it through the plug or on the separate port, just like you would with `mix exq.ui`

**Comment by akira** [comment]
Ah ok, great.  You can turn off the server via config:

```
config :exq_ui,
  server: false
```

**Comment by vrosancic** [comment]
Thanks!
