### ISSUE TITLE
Possible to silence logger?

### ISSUE THREAD

**Issue by daniel1943** [akira/exq_ui#44]
I don't want to change global logger level, possible to silence just exq_ui logger?

`[info] GET /exq/api/realtimes
[info] Sent 200 in 587µs
[info] GET /exq/api/realtimes
[info] Sent 200 in 599µs
[info] GET /exq/api/realtimes
[info] Sent 200 in 540µs
`
This is flooding console every second.

**Comment by akira** [comment]
That looks like it is coming from Phoenix and not Exq
