### ISSUE TITLE
Way to view on Heroku?

### ISSUE THREAD

**Issue by mlaythe** [akira/exq_ui#52]
Is there a way to view this dashboard in a deployed Heroku instance? Thanks! =)

**Comment by andreogle** [comment]
Did you manage to figure this out?

**Comment by punitcse** [comment]
@mlaythe @andreogle @akira  How can I view it on heroku can some one please help me regarding the same??

**Comment by coderberry** [comment]
+1

**Comment by ibash** [comment]
You can use the plug method to put the UI at a certain path: https://github.com/akira/exq_ui#using-with-plug
You'll probably want to put some sort of authentication around it, though.

**Comment by ibash** [comment]
You can use the plug method to put the UI at a certain path: https://github.com/akira/exq_ui#using-with-plug
You'll probably want to put some sort of authentication around it, though.

**Comment by jaimeiniesta** [comment]
Related: https://github.com/akira/exq_ui/issues/70
