### ISSUE TITLE
Avoid [Object object] in args column

### ISSUE THREAD

**Issue by alexcastano** [akira/exq_ui#58]
Hi,

Is there any way to avoid [Object object] in the args column? Actually, this object is just a simple map:

```elixir
%{id: "something"}
```
But I cannot see the id because the UI give this:

![image](https://user-images.githubusercontent.com/1745859/39377785-a545568e-4a56-11e8-86fc-83183b778062.png)

Any hack to fix it?

Thank you for your time

**Comment by quolpr** [comment]
+ the same problem

**Comment by Ninigi** [comment]
Since this still seems to be an open issue, I opened a PR #81 

@alexcastano you asked for a hack - until my PR is merged (if ever) - I am a custom built UI. You can access all the information with - for example - `Exq.Api.retries(Exq.Api)`.

In a phoenix project, to display retries I did something like this

```elixir
# DashboardController
  def index(conn, _params) do
    {:ok, retries} = Exq.Api.retries(Exq.Api)
    render(conn, "index.html", retries: retries)
  end
```
```eex
# index.html.eex
<table>
   <thead>
     <th>
       Class
     </th>
     <th>
       Error Class
     </th>
     <th>
       Error Message
     </th>
     <th>
       args
     </th>
   </thead>
   <tbody>
    <%= for retry <- @retries do %>
      <tr>
        <td>
          <%= inspect retry.class %>
        </td>
        <td>
          <%= inspect retry.error_class %>
        </td>
        <td>
          <%= retry.error_message %>
        </td>
        <td>
          <%= inspect retry.args %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
```

**Comment by akira** [comment]
I've merged this fix and published new version to hex, let me know if any issues.
