### ISSUE TITLE
Can't see enqueued tasks

### ISSUE THREAD

**Issue by jakub-zawislak** [akira/exq_ui#62]
When I click "Enqueued" or "Queues" I got this error:

> ember.debug.js:29019 Error while processing route: queues.index Assertion Failed: You must include an 'id' for queue in an object passed to 'push' Error: Assertion Failed: You must include an 'id' for queue in an object passed to 'push'

> ember.debug.js:18008 Error: Assertion Failed: You must include an 'id' for queue in an object passed to 'push'

There is no error, if there is no enqueued tasks.

**Comment by jakub-zawislak** [comment]
I think it happens when the `queue` key of some task is `nil`.

**Comment by ananthakumaran** [comment]
closing this, please reopen with more details if the issue still exists
