### ISSUE TITLE
Interested in an upgrade to the latest Ember version?

### ISSUE THREAD

**Issue by atonse** [akira/exq_ui#64]
We use (and love) exq for our Elixir/Ember application. I've noticed that you're having trouble maintaining the Ember version upgrades, etc. Would you like a PR to upgrade it further to the latest ember LTS version? (`3.4`)? Just want to make sure someone isn't already working on this.

**Comment by akira** [comment]
Hi,

Yes I am in general need of any help maintaining the app as I have a lot
going on. It will be great to have a PR for this!  Thanks!!

**Comment by atonse** [comment]
Good to know. Thank you for this useful tool. We'll add it to our development queue. Can't promise a date yet though.

**Comment by atonse** [comment]
Hi I did some work on this this past year and will continue to upgrade to even newer versions. We use ExqUI a lot and especially need it to be responsive.

Will keep you posted as we find time to work on this in small chunks.

**Comment by akira** [comment]
Closing as no longer on Ember
