### ISSUE TITLE
Cowboy 2.x support

### ISSUE THREAD

**Issue by jozefvaclavik** [akira/exq_ui#65]
Following https://gist.github.com/chrismccord/bb1f8b136f5a9e4abc0bfc07b832257e

While updating phoenix to 1.4 I'm switching `cowboy` to `plug_cowboy` but that requires `cowboy` `~>2.5`

```
Failed to use "cowboy" (versions 2.5.0 to 2.6.1) because
  exq_ui (version 0.9.0) requires ~> 1.0
  plug_cowboy (versions 2.0.0 and 2.0.1) requires ~> 2.5
```

**Comment by akira** [comment]
I haven't had a chance to release this new version. Does this work against master version of exq_ui?

I will release it shortly.

**Comment by jozefvaclavik** [comment]
@akira `master` is working for me too.

**Comment by akira** [comment]
I've just released a new version
