### ISSUE TITLE
Phoenix 1.4 static files

### ISSUE THREAD

**Issue by jozefvaclavik** [akira/exq_ui#68]
I upgraded to Phoenix 1.4 with webpack. And it's not fetching css and js exq assets. So the ember app is not loading.

<img width="1604" alt="screenshot 2019-01-21 at 14 11 37" src="https://user-images.githubusercontent.com/482174/51467890-0e58c580-1d87-11e9-8f11-676beb9a2c2b.png">

Doing `curl http://localhost:4000/exq/assets/vendor.js` from terminal returns this

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Exqui</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">


<meta name="exqui/config/environment" content="......." />

    <base href="/exq/" />

    <script>
      window.exqNamespace = "exq/";
    </script>

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/exqui.css">


  </head>
  <body>


    <script src="assets/vendor.js"></script>
    <script src="assets/exqui.js"></script>


  <iframe src="/phoenix/live_reload/frame" style="display: none;"></iframe>
</body>
</html>
```

Seems like something changed in routing static assets. Any ideas?
___
Edit: I'm running off `master` https://github.com/akira/exq_ui/commit/d3f2a519cdf64380ab39dc5be847a19ecfd3cede

**Comment by tonyc** [comment]
FWIW, I just ran into this too, although I'm not running Phoenix.

I'd agree that something with the asset serving is funky. I'm running off of master.
