### ISSUE TITLE
Disabling access via port when Plug access is enabled?

### ISSUE THREAD

**Issue by jaimeiniesta** [akira/exq_ui#70]
I've followed the guides on https://github.com/akira/exq_ui#using-with-plug and I have exq_ui working with this configuration:

```elixir
# *** config.ex ***

config :exq_ui,
  server: true

# *** router.ex ***

  pipeline :admin do
    plug(BasicAuth, use_config: {:myapp, :admin_auth})
  end

  pipeline :exq do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    plug ExqUi.RouterPlug, namespace: "admin/exq"
  end

  scope "/admin/exq", ExqUi do
    pipe_through [:admin, :exq]
    forward "/", RouterPlug.Router, :index
  end
```

This works fine and I can access http://localhost:4000/admin/exq and I'm prompted for my credentials, all fine.

But... I've found that I can also access http://localhost:4040 and I won't be prompted for credentials.

Is there a way to disable access and only enable it via the configured route?

**Comment by akira** [comment]
I believe you should be able to put the BasicAuth declaration outside the Admin block:

```
Add into the top of a controller, or into a router pipeline a plug declaration like:
plug BasicAuth, use_config: {:your_app, :your_config}
```
https://github.com/CultivateHQ/basic_auth

**Comment by taylordowns2000** [comment]
@akira , thanks for the swift response here. Would you explain this a bit more? (Or, @jaimeiniesta, if this worked for you, could you paste your changed code?)

I had thought that `router.ex` was only used for the phoenix app running on `:4000`, in Jamie's case. Does accessing exq at port `:4040` allow a request to even touch the router? I'm having the same issue—authentication is required when accessing `exq_ui` through the router and the basic auth pipeline, but not when accessing Exq directly via port `:4040`. My code below:

```ex
# config.exs
config :exq_ui,
  web_port: 4040,
  web_namespace: "exq",
  server: true
```

```ex
# router.ex
  pipeline :exq do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    plug BasicAuth, use_config: {:my_app, :admin}
    plug ExqUi.RouterPlug, namespace: "exq"
  end

  scope "/exq", ExqUi do
    pipe_through :exq
    forward "/", RouterPlug.Router, :index
  end
```

**Comment by jaimeiniesta** [comment]
Thanks @akira but like @taylordowns2000 I'm not having any problem in setting up BasicAuth on the access through the router. My code above, or the one that @taylordowns2000 puts here, both work fine.

But, when you access directly through the `:4040` port you're still able to see Exqui, without any authentication. How can this be disabled so the only way in is passing through the router?

**Comment by taylordowns2000** [comment]
Hey @jaimeiniesta , for me, this ended up not being a problem. I didn't realize this at first, but (of course!) my nginx config (and the firewall rules for connecting to my server) won't allow a direct connection to port `4040`—in other words, if I wanted to deploy this to staging or production and access it via the web, there's no way to get at `exq_ui` other than through the elixir app running at :4000, since that's the only "way in". Does that make sense?

**Comment by jaimeiniesta** [comment]
Hey @taylordowns2000 same here, I'm having no problems in practice with this as the `4040` is not exposed, but I still think this can be a security problem if it goes unnoticed in some cases.

I expected that by removing the `web_port` option from the config, no port would be exposed, but it defaults to `4040` so there's no way to disable it, it seems.

In my opinion the best way to fix this is implement https://github.com/akira/exq_ui/issues/12

**Comment by AdrianSchneider** [comment]
If you're using the plug and don't want the server listening automatically, setting this does the trick:

```elixir
config :exq_ui,
  server: false
```

The UI will still be accessible in your app wherever it's mounted, and the server will _not_ be accessible at :4040 anymore. I ran into this when attempting to compile / run `mix` while my server was already running and it would throw an error trying to listen on that port.
