### ISSUE TITLE
Workers table broken

### ISSUE THREAD

**Issue by jaimeiniesta** [akira/exq_ui#73]
When I click on Workers (`/exq/processes`) I often see this broken table:

![captura de pantalla 2019-02-25 10 24 09](https://user-images.githubusercontent.com/2629/53328399-283b7a00-38ea-11e9-806e-dfce1cd59b5d.png)

And sometimes it's not broken but it's missing data:

![captura de pantalla 2019-02-25 10 36 07](https://user-images.githubusercontent.com/2629/53328426-34bfd280-38ea-11e9-991c-ffd006812946.png)

Other tables like the one for Scheduled looks fine, with all its data.

**Comment by ananthakumaran** [comment]
closing this. feel free to re-open if this is still an issue on the latest version.
