### ISSUE TITLE
Dashboard graph is just gray

### ISSUE THREAD

**Issue by jaimeiniesta** [akira/exq_ui#74]
Is it normal that the graph on Dashboard looks like this, using only one colour?

![captura de pantalla 2019-02-25 10 24 53](https://user-images.githubusercontent.com/2629/53328510-751f5080-38ea-11e9-902e-89a20bd26c2d.png)

I'm using the default view (I didn't follow the instructions to set up Ember).

**Comment by ananthakumaran** [comment]
The library has been rewritten and this shouldn't happen in the latest version.
