### ISSUE TITLE
What is size in queue? And why does it show a bigger number than the total scheduled queue?

### ISSUE THREAD

**Issue by shijithkjayan** [akira/exq_ui#86]
![2019-12-11 16 15 20 copy](https://user-images.githubusercontent.com/41006127/70617381-81388c80-1c36-11ea-847c-a6d28bdf8543.jpg)
This is not a big, but more of a doubt. There are several jobs scheduled under multiple queues, but the size has a value other than zero only for one of the queues. Also, the size is bigger than the total number of scheduled jobs. Can someone tell me why is that happening and what exactly is this size?

**Comment by ananthakumaran** [comment]
Queue size here means the number of jobs available to be picked up by workers. Scheduled jobs are not counted as they are not yet ready for pickup.
