### ISSUE TITLE
Stats should poll to update

### ISSUE THREAD

**Issue by akira** [akira/exq_ui#9]
Right now the chart updates but we should also be updating the stats at the top of the page with the latest stats.

Moved from https://github.com/akira/exq/issues/49

**Comment by andrewvy** [comment]
Taking a stab at this. I'm refactoring "stats" into an Ember service, which can be updated from any source, and injected into the `exq-stats` component.

Then, [index route](https://github.com/akira/exq_ui/blob/master/priv/ember/app/routes/index.coffee) can just automatically update the service and increment the stat values.

**Comment by akira** [comment]
:+1:

**Comment by ananthakumaran** [comment]
This has been done on the latest release
